"""Add rate_limit_hits table for distributed rate limiting.

Revision ID: 5b3c4d2e8f9a
Revises: 4f2a1e9c7b10
Create Date: 2026-03-17 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5b3c4d2e8f9a"
down_revision: Union[str, Sequence[str], None] = "4f2a1e9c7b10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_hits",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key", sa.String(255), nullable=False),
        sa.Column("hit_at", sa.DateTime(timezone=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rate_limit_hits_key", "rate_limit_hits", ["key"], unique=False)
    op.create_index("ix_rate_limit_hits_hit_at", "rate_limit_hits", ["hit_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rate_limit_hits_hit_at", table_name="rate_limit_hits")
    op.drop_index("ix_rate_limit_hits_key", table_name="rate_limit_hits")
    op.drop_table("rate_limit_hits")
    # ### end Alembic commands ###
