"""Add token_hash column to invitations table for secure token comparison.

Revision ID: 6c5d7e4f8a2b
Revises: 5b3c4d2e8f9a
Create Date: 2026-03-17 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6c5d7e4f8a2b"
down_revision: Union[str, Sequence[str], None] = "5b3c4d2e8f9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invitations", sa.Column("token_hash", sa.String(64), nullable=True))
    op.create_index("ix_invitations_token_hash", "invitations", ["token_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_invitations_token_hash", table_name="invitations")
    op.drop_column("invitations", "token_hash")
    # ### end Alembic commands ###
